# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql-root-password
#   # annotations:
#   #   secret-generator.v1.mittwald.de/autogenerate: password
# data:
#   password: d29vcGVyCg==

apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
type: kubernetes.io/basic-auth
stringData:
  password: wooper