resources:
- ../base
- mysql/deployment.yaml
- mysql/pvc.yaml
- mysql/secrets.yaml
- ghost/ingress.yaml
- ghost/tls-secret.yaml

configMapGenerator:
  - name: ghost-configmap
    namespace: ghost
    envs:
      - .env.ghost
