apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - image: ghost:5.11
        name: ghost
        env:
        - name: database__client
          value: mysql
        - name: database__connection__database
          value: ghost
        - name: database__connection__host
          value: mysql
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: password
        - name: database__connection__user
          value: root
        # patch
        - name: NODE_ENV
          value: development
        - name: url
          value: https://localhost
        ports:
        - containerPort: 2368
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: ghost
spec:
  selector:
    app: ghost
  ports:
  - port: 80
    targetPort: 2368