apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - image: ghost:5.11
        name: ghost
        env:
        - name: database__client
          value: mysql
        - name: database__connection__database
          valueFrom:
            configMapKeyRef:
              name: ghost-configmap
              key: database__connection__database
        - name: database__connection__host
          valueFrom:
            configMapKeyRef:
              name: ghost-configmap
              key: database__connection__host
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: password
        - name: database__connection__user
          valueFrom:
            configMapKeyRef:
              name: ghost-configmap
              key: database__connection__user
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ghost-configmap
              key: NODE_ENV
        - name: url
          valueFrom:
            configMapKeyRef:
              name: ghost-configmap
              key: url
        ports:
        - containerPort: 2368
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ghost
spec:
  selector:
    app: ghost
  ports:
  - port: 80
    targetPort: 2368